name: painter_ok_done
description: Utils package for ok_done
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
  
dependencies:
  flutter:
    sdk: flutter
